version: "3.8"
services:
  user-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: user_service_db
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - user-db-data:/var/lib/mysql
    ports:
      - "33061:3306"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      APP_ENV: local
      DB_HOST: user-db
      DB_DATABASE: user_service_db
      DB_USERNAME: user
      DB_PASSWORD: secret
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - user-db
      - rabbitmq
    ports:
      - "8001:80"
    volumes:
      - ./user-service:/var/www/html

volumes:
  user-db-data:
